- name: Install Python 2.6
  yum: name=python26 state=latest
  tags:
    - python

- name: Install python-ssl
  yum: name=python-ssl state=latest
  tags:
    - python

- name: Download get-pip.py
  get_url: url=https://bootstrap.pypa.io/get-pip.py dest=/tmp/get-pip.py
  tags:
    - python

- name: Run get-pip.py
  command: python2.6 /tmp/get-pip.py
  tags:
    - python
