# Deploy service nginx containers. This should be run when first setting up
# zero-downtime deployment and when the image has changed (including when the
# configuration template has changed). Restarting these containers is not a
# zero-downtime game, so it should be kept minimal. Luckily, these are very
# simple containers.
---

- name: predeploy chat notification
  hosts: services:ui:&systems
  become: true
  gather_facts: false
  tags:
    - always
  roles:
    - role: util-notify-chat
      msg: "Deploying service nginxes"

- name: Redeploy anon-files-nginx
  hosts: anon-files:&systems
  become: true
  gather_facts: false
  tags:
    - services
    - anon-files
  roles:
    - role: de-deploy-service
      has_configs: false
      has_iplant_data: false
      deploy_use_color: false
      force_recreate: false
      service_name: "{{anon_files.compose_service}}_nginx"

- name: Redeploy apps-nginx
  hosts: apps:&systems
  become: true
  gather_facts: false
  tags:
    - services
    - apps
  roles:
    - role: de-deploy-service
      has_configs: false
      has_iplant_data: false
      deploy_use_color: false
      force_recreate: false
      service_name: "{{apps.compose_service}}_nginx"

- name: Redeploy data-info-nginx
  hosts: data-info:&systems
  become: true
  gather_facts: false
  tags:
    - services
    - data-info
  roles:
    - role: de-deploy-service
      has_configs: false
      has_iplant_data: false
      deploy_use_color: false
      force_recreate: false
      service_name: "{{data_info.compose_service}}_nginx"

- name: Redeploy iplant-email-nginx
  hosts: iplant-email:&systems
  become: true
  gather_facts: false
  tags:
    - services
    - iplant-email
  roles:
    - role: de-deploy-service
      has_configs: false
      has_iplant_data: false
      deploy_use_color: false
      force_recreate: false
      service_name: "{{iplant_email.compose_service}}_nginx"

- name: Redeploy iplant-groups-nginx
  hosts: iplant-groups:&systems
  become: true
  gather_facts: false
  tags:
    - services
    - iplant-groups
  roles:
    - role: de-deploy-service
      has_configs: false
      has_iplant_data: false
      deploy_use_color: false
      force_recreate: false
      service_name: "{{iplant_groups.compose_service}}_nginx"

- name: Redeploy jex-adapter-nginx
  hosts: jexevents
  sudo: true
  gather_facts: false
  tags:
    - services
    - jex-adapter
  roles:
    - role: de-deploy-service
      has_configs: false
      has_iplant_data: false
      deploy_use_color: false
      force_recreate: false
      service_name: jex_adapter_nginx

- name: Redeploy kifshare-nginx
  hosts: kifshare:&systems
  become: true
  gather_facts: false
  tags:
    - services
    - kifshare
  roles:
    - role: de-deploy-service
      has_configs: false
      has_iplant_data: false
      deploy_use_color: false
      force_recreate: false
      service_name: "{{kifshare.compose_service}}_nginx"

- name: Redeploy metadata-nginx
  hosts: metadata:&systems
  become: true
  gather_facts: false
  tags:
    - services
    - metadata
  roles:
    - role: de-deploy-service
      has_configs: false
      has_iplant_data: false
      deploy_use_color: false
      force_recreate: false
      service_name: "{{metadata.compose_service}}_nginx"

- name: Redeploy notification-agent-nginx
  hosts: notificationagent:&systems
  become: true
  gather_facts: false
  tags:
    - services
    - notificationagent
  roles:
    - role: de-deploy-service
      has_configs: false
      has_iplant_data: false
      deploy_use_color: false
      force_recreate: false
      service_name: "{{notificationagent.compose_service}}_nginx"

- name: Redeploy permissions-nginx
  hosts: permissions:&systems
  become: true
  gather_facts: false
  tags:
    - services
    - permissions
  roles:
    - role: de-deploy-service
      has_configs: false
      has_iplant_data: false
      deploy_use_color: false
      force_recreate: false
      service_name: "{{permissions.compose_service}}_nginx"

- name: Redeploy saved-searches-nginx
  hosts: saved-searches:&systems
  become: true
  gather_facts: false
  tags:
    - services
    - saved-searches
  roles:
    - role: de-deploy-service
      has_configs: false
      has_iplant_data: false
      deploy_use_color: false
      force_recreate: false
      service_name: "{{saved_searches.compose_service}}_nginx"

- name: Redeploy terrain-nginx
  hosts: terrain:&systems
  become: true
  gather_facts: false
  tags:
    - services
    - terrain
  roles:
    - role: de-deploy-service
      has_configs: false
      has_iplant_data: false
      deploy_use_color: false
      force_recreate: false
      service_name: "{{terrain.compose_service}}_nginx"

- name: Redeploy tree-urls-nginx
  hosts: tree-urls:&systems
  become: true
  gather_facts: false
  tags:
    - services
    - tree-urls
  roles:
    - role: de-deploy-service
      has_configs: false
      has_iplant_data: false
      deploy_use_color: false
      force_recreate: false
      service_name: "{{tree_urls.compose_service}}_nginx"

- name: Redeploy user-preferences-nginx
  hosts: user-preferences:&systems
  become: true
  gather_facts: false
  tags:
    - services
    - user-preferences
  roles:
    - role: de-deploy-service
      has_configs: false
      has_iplant_data: false
      deploy_use_color: false
      force_recreate: false
      service_name: "{{user_preferences.compose_service}}_nginx"

- name: Redeploy user-sessions-nginx
  hosts: user-sessions:&systems
  become: true
  gather_facts: false
  tags:
    - services
    - user-sessions
  roles:
    - role: de-deploy-service
      has_configs: false
      has_iplant_data: false
      deploy_use_color: false
      force_recreate: false
      service_name: "{{user_sessions.compose_service}}_nginx"

- name: Redeploy de-ui-nginx
  hosts: ui:&systems
  become: true
  gather_facts: false
  tags:
    - ui
    - de-ui-nginx
  roles:
    - role: de-deploy-service
      has_iplant_data: true
      deploy_use_color: false
      service_name: "{{de.http_server.compose_service}}"

- name: postdeploy chat notification
  hosts: services:ui:&systems
  become: true
  gather_facts: false
  tags:
    - always
  roles:
    - role: util-notify-chat
      msg: ":heavy_check_mark: Done deploying service nginxes"
