---
- name: Start anon-files
  hosts: anon-files:&systems
  become: true
  gather_facts: false
  tags:
    - services
    - anon-files
  roles:
    - role: util-cfg-docker-up
      service_name: "{{anon_files.compose_service}}"
      service_name_short: "{{anon_files.service_name_short}}"

- name: Start apps
  hosts: apps:&systems
  become: true
  gather_facts: false
  tags:
    - services
    - apps
  roles:
    - role: util-cfg-docker-up
      service_name: "{{apps.compose_service}}"
      service_name_short: "{{apps.service_name_short}}"

- name: Start clockwork
  hosts: clockwork:&systems
  become: true
  gather_facts: false
  tags:
    - services
    - clockwork
  roles:
    - role: util-cfg-docker-up
      service_name: "{{clockwork.compose_service}}"
      service_name_short: "{{clockwork.service_name_short}}"

- name: Start data-info
  hosts: data-info:&systems
  become: true
  gather_facts: false
  tags:
    - services
    - data-info
  roles:
    - role: util-cfg-docker-up
      service_name: "{{data_info.compose_service}}"
      service_name_short: "{{data_info.service_name_short}}"

- name: Start dewey
  hosts: dewey:&systems
  become: true
  gather_facts: false
  tags:
    - services
    - dewey
  roles:
    - role: util-cfg-docker-up
      when: not parasitic
      service_name: "{{dewey.compose_service}}"
      service_name_short: "{{dewey.service_name_short}}"

- name: Start de-ui
  hosts: ui:&systems
  become: true
  gather_facts: false
  tags:
    - ui
  roles:
    - role: util-cfg-docker-up
      service_name: "{{de.compose_service}}"
      service_name_short: "{{de.service_name_short}}"

- name: Start de-ui-nginx
  hosts: ui:&systems
  become: true
  gather_facts: false
  tags:
    - ui
    - de-ui-nginx
  roles:
    - role: util-cfg-docker-up
      service_name: "{{de.http_server.compose_service}}"
      service_name_short: "{{de.http_server.service_name_short}}"

- name: Start exim-sender
  hosts: exim-sender:&systems
  become: true
  gather_facts: false
  tags:
    - services
    - exim-sender
  roles:
    - role: util-cfg-docker-up
      service_name: "{{exim.compose_service}}"
      service_name_short: "{{exim.service_name_short}}"

- name: Start info-typer
  hosts: info-typer:&systems
  become: true
  gather_facts: false
  tags:
    - services
    - info-typer
  roles:
    - role: util-cfg-docker-up
      when: not parasitic
      service_name: "{{info_typer.compose_service}}"
      service_name_short: "{{info_typer.service_name_short}}"

- name: Start infosquito
  hosts: infosquito:&systems
  become: true
  gather_facts: false
  tags:
    - services
    - infosquito
  roles:
    - role: util-cfg-docker-up
      when: not parasitic
      service_name: "{{infosquito.compose_service}}"
      service_name_short: "{{infosquito.service_name_short}}"

- name: Start iplant-email
  hosts: iplant-email:&systems
  become: true
  gather_facts: false
  tags:
    - services
    - iplant-email
  roles:
    - role: util-cfg-docker-up
      service_name: "{{iplant_email.compose_service}}"
      service_name_short: "{{iplant_email.service_name_short}}"

- name: Start iplant-groups
  hosts: iplant-groups:&systems
  become: true
  gather_facts: false
  tags:
    - services
    - iplant-groups
  roles:
    - role: util-cfg-docker-up
      service_name: "{{iplant_groups.compose_service}}"
      service_name_short: "{{iplant_groups.service_name_short}}"

- name: Start jex-adapter
  hosts: jexevents
  sudo: true
  gather_facts: false
  tags:
    - services
    - jex-adapter
  roles:
    - role: util-cfg-docker-up
      service_name: jex_adapter
      service_name_short: jex_adapter

- name: Start job-status-to-apps-adapter
  hosts: jexevents
  sudo: true
  gather_facts: false
  tags:
    - services
    - job-status-to-apps-adapter
  roles:
    - role: util-cfg-docker-up
      service_name: job_status_to_apps_adapter
      service_name_short: job_status_to_apps_adapter

- name: Start job-status-recorder
  hosts: jexevents
  sudo: true
  gather_facts: false
  tags:
    - services
    - job-status-recorder
  roles:
    - role: util-cfg-docker-up
      service_name: job_status_recorder
      service_name_short: job_status_recorder

- name: Start kifshare
  hosts: kifshare:&systems
  become: true
  gather_facts: false
  tags:
    - services
    - kifshare
  roles:
    - role: util-cfg-docker-up
      service_name: "{{kifshare.compose_service}}"
      service_name_short: "{{kifshare.service_name_short}}"

- name: Start metadata
  hosts: metadata:&systems
  become: true
  gather_facts: false
  tags:
    - services
    - metadata
  roles:
    - role: util-cfg-docker-up
      service_name: "{{metadata.compose_service}}"
      service_name_short: "{{metadata.service_name_short}}"

- name: Start monkey
  hosts: monkey:&systems
  become: true
  gather_facts: false
  tags:
    - services
    - monkey
  roles:
    - role: util-cfg-docker-up
      when: not parasitic
      service_name: "{{monkey.compose_service}}"
      service_name_short: "{{monkey.service_name_short}}"

- name: Start notification-agent
  hosts: notificationagent:&systems
  become: true
  gather_facts: false
  tags:
    - services
    - notificationagent
  roles:
    - role: util-cfg-docker-up
      service_name: "{{notificationagent.compose_service}}"
      service_name_short: "{{notificationagent.service_name_short}}"

- name: Start permissions
  hosts: permissions:&systems
  become: true
  gather_facts: false
  tags:
    - services
    - permissions
  roles:
    - role: util-cfg-docker-up
      service_name: "{{permissions.compose_service}}"
      service_name_short: "{{permissions.service_name_short}}"

- name: Start saved-searches
  hosts: saved-searches:&systems
  become: true
  gather_facts: false
  tags:
    - services
    - saved-searches
  roles:
    - role: util-cfg-docker-up
      service_name: "{{saved_searches.compose_service}}"
      service_name_short: "{{saved_searches.service_name_short}}"

- name: Start templeton-periodic
  hosts: templeton-periodic:&systems
  become: true
  gather_facts: false
  tags:
    - services
    - templeton
    - templeton-periodic
  roles:
    - role: util-cfg-docker-up
      when: not parasitic
      service_name: "{{templeton_periodic.compose_service}}"
      service_name_short: "{{templeton_periodic.service_name_short}}"

- name: Start templeton-incremental
  hosts: templeton-incremental:&systems
  become: true
  gather_facts: false
  tags:
    - services
    - templeton
    - templeton-incremental
  roles:
    - role: util-cfg-docker-up
      when: not parasitic
      service_name: "{{templeton_incremental.compose_service}}"
      service_name_short: "{{templeton_incremental.service_name_short}}"

- name: Start terrain
  hosts: terrain:&systems
  become: true
  gather_facts: false
  tags:
    - services
    - terrain
  roles:
    - role: util-cfg-docker-up
      service_name: "{{terrain.compose_service}}"
      service_name_short: "{{terrain.service_name_short}}"

- name: Start tree-urls
  hosts: tree-urls:&systems
  become: true
  gather_facts: false
  tags:
    - services
    - tree-urls
  roles:
    - role: util-cfg-docker-up
      service_name: "{{tree_urls.compose_service}}"
      service_name_short: "{{tree_urls.service_name_short}}"

- name: Start user-preferences
  hosts: user-preferences:&systems
  become: true
  gather_facts: false
  tags:
    - services
    - user-preferences
  roles:
    - role: util-cfg-docker-up
      service_name: "{{user_preferences.compose_service}}"
      service_name_short: "{{user_preferences.service_name_short}}"

- name: Start user-sessions
  hosts: user-sessions:&systems
  become: true
  gather_facts: false
  tags:
    - services
    - user-sessions
  roles:
    - role: util-cfg-docker-up
      service_name: "{{user_sessions.compose_service}}"
      service_name_short: "{{user_sessions.service_name_short}}"
