# Set de_config_dir to the local directory.
# Example: ansible-playbook -i inventories/production.cfg  --extra-vars "de_config_dir=$(pwd)/foo playbook=playbooks/local-services-cfg.yml owner=$(whoami) group=staff de_env=production" --tags="service_config,logging_config" single-role.yaml

---
- hosts: localhost
  sudo: false
  gather_facts: false
  vars_files:
    - ../group_vars/{{de_env}}
  pre_tasks:
    - name: create the output directory
      file: path={{de_config_dir}} state=directory
      tags:
        - service_config

    - name: create the logging directory
      file: path={{de_config_dir}}/logging state=directory
      tags:
        - logging_config

    - name: create the logstash-forwarder directory
      file: path={{de_config_dir}}/logstash-forwarder state=directory
      tags:
        - logging_config

    - name: create the nginx config
      file: path={{de_config_dir}}/nginx state=directory
      tags:
        - service_config

  roles:
    - role: util-cfg-service
      service_name_short: "{{anon_files.service_name_short}}"

    - role: util-cfg-service
      service_name_short: "{{apps.service_name_short}}"

    - role: util-cfg-service
      service_name_short: "{{clockwork.service_name_short}}"

    - role: util-cfg-service
      service_name_short: "{{condor_log_monitor.service_name_short}}"

    - role: util-cfg-service
      service_name_short: "{{data_info.service_name_short}}"

    - role: util-cfg-service
      service_name_short: "{{dewey.service_name_short}}"

    - role: util-cfg-service
      service_name_short: "{{exim.service_name_short}}"

    - role: util-cfg-service
      service_name_short: "{{info_typer.service_name_short}}"

    - role: util-cfg-service
      service_name_short: "{{infosquito.service_name_short}}"

    - role: util-cfg-service
      service_name_short: "{{iplant_email.service_name_short}}"

    - role: util-cfg-service
      service_name_short: "{{iplant_groups.service_name_short}}"

    - role: util-cfg-service
      service_name_short: "{{jexevents.service_name_short}}"

    - role: util-cfg-service
      service_name_short: "{{kifshare.service_name_short}}"

    - role: util-cfg-service
      service_name_short: "{{metadata.service_name_short}}"

    - role: util-cfg-service
      service_name_short: "{{monkey.service_name_short}}"

    - role: util-cfg-service
      service_name_short: "{{notificationagent.service_name_short}}"

    - role: util-cfg-service
      service_name_short: "{{saved_searches.service_name_short}}"

    - role: util-cfg-service
      service_name_short: "{{terrain.service_name_short}}"

    - role: util-cfg-service
      service_name_short: "{{tree_urls.service_name_short}}"

    - role: util-cfg-service
      service_name_short: "{{user_preferences.service_name_short}}"

    - role: util-cfg-service
      service_name_short: "{{user_sessions.service_name_short}}"

    - role: util-cfg-service
      src: "ui/de-application.yaml.j2"
      dest: "{{service_conf_dir}}/de-application.yaml"
      service_name_short: "{{de.service_name_short}}"

    - role: util-cfg-service
      src: "ui/de.properties.j2"
      dest: "{{service_conf_dir}}/de.properties"
      service_name_short: "{{de.service_name_short}}"

    - role: util-cfg-service
      src: "ui/nginx.conf.j2"
      dest: "{{service_conf_dir}}/nginx.conf"
      service_name_short: "{{de.service_name_short}}"

    # - role: util-cfg-service
    #   src: "logstash-forwarder/logstash-forwarder-conf.json.j2"
    #   dest: "{{service_conf_dir}}/logstash-forwarder/config.json"
    #   service_name_short: "{{logstash_forwarder.service_name_short}}"

    - role: util-cfg-service
      src: "docker-cleanup/docker-gc-exclude-containers.j2"
      dest: "{{service_conf_dir}}/docker-gc-exclude-containers"
      service_name_short: "docker-gc"

    - role: util-cfg-service
      src: "docker-cleanup/docker-gc-exclude.j2"
      dest: "{{service_conf_dir}}/docker-gc-exclude"
      service_name_short: "docker-gc"
