---
# tasks file for cfg-docker-pull
#

- debug: msg="Removing {{service_name}}"
  tags:
      - docker_rm

- name: remove the {{service_name}} container
  environment:
    DE_TAG: "{{docker.tag}}"
    DE_ENV: "{{environment_name}}"
    HOSTNAME: "{{inventory_hostname}}"
  shell: "docker-compose -f {{docker_compose_path}} rm -f -v {{service_name}}"
  register: docker_pull_v
  changed_when: docker_pull_v.stdout.find('Image is up to date') == -1
  ignore_errors: yes
  tags:
    - docker_rm
