---
# Verifies that all services are running in the appropriate hosts
#
# ansible-playbook -i inventories/.. -K verify-systemd-services-running.yaml
#
### Only verify (services,ui,elk,docker-ready) hosts
# ansible-playbook -i inventories/.. -K --tags "services" verify-systemd-services-running.yaml
# ansible-playbook -i inventories/.. -K --tags "ui" verify-systemd-services-running.yaml
# ansible-playbook -i inventories/.. -K --tags "elk" verify-systemd-services-running.yaml
# ansible-playbook -i inventories/.. -K --tags "docker-ready" verify-systemd-services-running.yaml

- name: Verify services enabled on service hosts
  hosts: services
  sudo: yes
  tasks:
      - name: services are enabled
        shell: systemctl is-enabled {{item.service_name}}
        register: verify_services_enabled
        ignore_errors: yes
        with_items: 
                  - "{{data_info}}"
                  - "{{anon_files}}"
                  - "{{condor_log_monitor}}"
                  - "{{clockwork}}"
                  - "{{donkey}}"
                  - "{{iplant_email}}"
                  - "{{iplant_groups}}"
                  - "{{exim}}"
                  - "{{jexevents}}"
                  - "{{kifshare}}"
                  - "{{metadactyl}}"
                  - "{{metadata}}"
                  - "{{notificationagent}}"
                  - "{{saved_searches}}"
                  - "{{tree_urls}}"
                  - "{{user_preferences}}"
                  - "{{user_sessions}}"
                  - "{{jex}}"
        tags:
            - services


      - fail: msg="{{item.item.service_name}} does not appear to be enabled"
        when: item.rc != 0
        with_items: "{{verify_services_enabled.results}}"
        tags:
            - services

      - name: non-parasitic services are enabled
        shell: systemctl is-enabled {{item.service_name}}
        register: verify_non_parasitic_services_enabled
        ignore_errors: yes
        when: not parasitic
        with_items:
                  - "{{dewey}}"
                  - "{{infosquito}}"
                  - "{{info_typer}}"
                  - "{{monkey}}"
        tags:
            - services


      - fail: msg="{{item.item.service_name}} does not appear to be enabled"
        when: not parasitic and item.rc != 0
        with_items: "{{verify_non_parasitic_services_enabled.results}}"
        tags:
            - services


- name: Verify services enabled on ui hosts
  hosts: ui
  sudo: yes
  tasks: 
      - name: services are enabled
        shell: systemctl is-enabled {{item.service_name}}
        register: verify_services_enabled
        ignore_errors: yes
        with_items: 
                  - "{{de}}"
                  - "{{de.http_server}}"
        tags:
            - ui

      - fail: msg="{{item.item.service_name}} does not appear to be running"
        when: item.rc != 0
        with_items: "{{verify_services_enabled.results}}"
        tags:
            - ui


- name: Verify services enabled on elk hosts
  hosts: elk
  sudo: yes
  tasks: 
      - name: services are enabled
        shell: systemctl is-enabled {{item.service_name}}
        register: verify_services_enabled
        ignore_errors: yes
        with_items: 
                  - "{{elk.elasticsearch}}"
                  - "{{elk.kibana}}"
                  - "{{elk.logstash}}"
        tags:
            - elk

      - fail: msg="{{item.item.service_name}} does not appear to be enabled"
        when: item.rc != 0
        with_items: "{{verify_services_enabled.results}}"
        tags:
            - elk


- name: Verify services enabled on docker-ready hosts
  hosts: docker-ready
  sudo: yes
  tasks: 
      - name: services are enabled
        shell: systemctl is-enabled {{item.service_name}}
        register: verify_services_enabled
        ignore_errors: yes
        with_items: 
                  - "{{logstash_forwarder}}"
        tags:
            - docker_ready

      - fail: msg="{{item.item.service_name}} does not appear to be enabled"
        when: item.rc != 0
        with_items: "{{verify_services_enabled.results}}"
        tags:
            - docker_ready


