# Determines the current color (blue or green) of a service using consul, then delegates to swap-service.yaml to deploy based on this information.
---

- include: check-service.yaml
  vars:
    check_service_name: "{{service_name}}_green"
    available_services: "{{service_list.stdout_lines}}"
  tags:
      - verify

- include: check-service.yaml
  vars:
    check_service_name: "{{service_name}}_blue"
    available_services: "{{service_list.stdout_lines}}"
  tags:
      - verify

- include: check-service.yaml
  vars:
    check_service_name: "config_{{service_name}}_green"
    available_services: "{{service_list.stdout_lines}}"
  tags:
      - verify
  when: has_configs|default(true)

- include: check-service.yaml
  vars:
    check_service_name: "config_{{service_name}}_blue"
    available_services: "{{service_list.stdout_lines}}"
  tags:
      - verify
  when: has_configs|default(true)

- include: check-service.yaml
  vars:
    check_service_name: "iplant_data_{{service_name}}_green"
    available_services: "{{service_list.stdout_lines}}"
  tags:
      - verify
  when: has_iplant_data|default(false)

- include: check-service.yaml
  vars:
    check_service_name: "iplant_data_{{service_name}}_blue"
    available_services: "{{service_list.stdout_lines}}"
  tags:
      - verify
  when: has_iplant_data|default(false)

- name: Determine color of {{service_name_short}}
  shell: "curl -f http://localhost:{{consul_port}}/v1/kv/{{environment_name}}/{{service_name_short}}/color?raw || printf 'green'"
  args:
    warn: no
  register: service_color_check

- debug: msg="Color of {{service_name}} is {{service_color_check.stdout_lines[0]}}"

- include: swap-service.yaml
  vars:
      current_color: "green"
      other_color: "blue"
  when: service_color_check.stdout_lines[0] == 'green'

- include: swap-service.yaml
  vars:
      current_color: "blue"
      other_color: "green"
  when: service_color_check.stdout_lines[0] == 'blue'
