# Delegates to restart-service.yaml, since uncolored deployment simply restarts the service.
---

- include: check-service.yaml
  vars:
    check_service_name: "{{service_name}}"
    available_services: "{{service_list.stdout_lines}}"
  tags:
      - verify

- include: check-service.yaml
  vars:
    check_service_name: "config_{{service_name}}"
    available_services: "{{service_list.stdout_lines}}"
  tags:
      - verify
  when: has_configs|default(true)

- include: check-service.yaml
  vars:
    check_service_name: "iplant_data_{{service_name}}"
    available_services: "{{service_list.stdout_lines}}"
  tags:
      - verify
  when: has_iplant_data|default(false)

- include: restart-service.yaml
  vars:
    restart_service_name: "{{service_name}}"
